### ISSUE TITLE
Python3 update?

### ISSUE THREAD

**Issue by zyxep** [amendlik/salt-gen-resource#11]
Hey,

I was cloning this repo to my Rundeck server as per readme and then i tried to run the script.
it was not happy about `#!/usr/bin/env python` 
i am on a brand new ubuntu 22.04 server, changing python to python3 fixed the executable :)

**Comment by amendlik** [comment]
Unlike most other distributions, Ubuntu does not provide a `python` executable when you install Python. Installing the `python-is-python3` will correct that.
