### ISSUE TITLE
pip3 + salt package

### ISSUE THREAD

**Issue by zyxep** [amendlik/salt-gen-resource#12]
Hey,

On this new install i have, i had to install pip3 & then `pip3 install salt` to make the script run.
the docs didn't say anything about it.

**Comment by blu-base** [comment]
This plugin assumes that a salt-minion is running on the rundeck server. 
Having a salt-minion running implicitly means the salt package has to be available already.

Though, if your salt-minion is running in a virtual environment you'd yield your observation.

**Comment by valentin2105** [comment]
Same, with salt 3006.2, I had to `pip3 install salt` to make it work.

**Comment by amendlik** [comment]
I don't see an issue here. The documentation is clear that this plugin requires a working Salt minion. Please see the Salt documentation for those instructions.
